
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#FFFFFF")

def draw_rounded_rectangle(canvas, x, y, width, height, radius, color):
    canvas.create_rectangle(
        x + radius,
        y,
        x + width - radius,
        y + height,
        fill=color,
        outline=color
    )
    canvas.create_rectangle(
        x,
        y + radius,
        x + width,
        y + height - radius,
        fill=color,
        outline=color
    )
    canvas.create_oval(
        x,
        y,
        x + 2 * radius,
        y + 2 * radius,
        fill=color,
        outline=color
    )
    canvas.create_oval(
        x + width - 2 * radius,
        y,
        x + width,
        y + 2 * radius,
        fill=color,
        outline=color
    )
    canvas.create_oval(
        x,
        y + height - 2 * radius,
        x + 2 * radius,
        y + height,
        fill=color,
        outline=color
    )
    canvas.create_oval(
        x + width - 2 * radius,
        y + height - 2 * radius,
        x + width,
        y + height,
        fill=color,
        outline=color
    )

def draw_circle(canvas, x, y, diameter, color):
    canvas.create_oval(x, y, x + diameter, y + diameter, fill=color, outline="")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
# bg rectangle
canvas.create_rectangle(
    483.0,
    129.0,
    1437.0,
    952.0,
    fill="#332222",
    outline="")

draw_rounded_rectangle(canvas, 623.0, 362.0, 1298.0-623.0, 451.0-362.0, 35, "#800909")

draw_rounded_rectangle(canvas, 623.0, 540.0, 1298.0-623.0, 629.0-540.0, 35, "#800909")

#circle bg
draw_circle(canvas, 557, 340.0, 689.0 - 557.0, "#D9D9D9")

#head
draw_circle(canvas, 600, 360.0, 646.0 - 600.0, "#999999")

#body
x1, y1 = 584.0, 406.0
x2, y2 = 663.0, 494.0

canvas.create_arc(
    x1, y1, x2, y2,
    start=357, extent=186,
    fill="#999999", outline=""
)

#circle bg
draw_circle(canvas, 1232.0, 519.0, 1364.0 - 1232.0, "#D9D9D9")

#head
draw_circle(canvas, 1275.0, 539.0, 1321.0 - 1275.0, "#999999")

#body
x1, y1 = 1259.0, 585.0
x2, y2 = 1338.0, 673.0

canvas.create_arc(
    x1, y1, x2, y2,
    start=357, extent=186,
    fill="#999999", outline=""
)

draw_rounded_rectangle(canvas, 623.0, 732.0, 1298.0-623.0, 821.0-732.0, 35, "#800909")

draw_circle(canvas, 557, 711.0, 689.0 - 557.0, "#D9D9D9")

#head
draw_circle(canvas, 600, 731.0, 646.0 - 600.0, "#999999")

#body
x1, y1 = 584.0, 777.0
x2, y2 = 663.0, 865.0

canvas.create_arc(
    x1, y1, x2, y2,
    start=357, extent=186,
    fill="#999999", outline=""
)

canvas.create_text(
    909.0,
    179.0,
    anchor="nw",
    text="DM\n",
    fill="#FFFFFF",
    font=("Inter", 60 * -1)
)
window.resizable(False, False)
window.mainloop()
